(ns mongol-date-picker.contants)

(def months
  (map #(str %)
       (range 1 13)))

(def en-months
  ["January"
   "February"
   "March"
   "April"
   "May"
   "June"
   "July"
   "August"
   "September"
   "October"
   "November"
   "December"])

(def mn-months 
  ["ᠨᠢᠭᠡ"
   "ᠬᠣᠶᠠᠷ"
   "ᠭᠤᠷᠪᠠ"
   "ᠳᠦᠷᠪᠡ"
   "ᠲᠠᠪᠤ"
   "ᠵᠢᠷᠭᠤᠭ᠎ᠠ"
   "ᠳᠣᠯᠣᠭ᠎ᠠ"
   "ᠨᠠᠢᠮᠠ"
   "ᠶᠢᠰᠦ"
   "ᠠᠷᠪᠠ"
   "ᠠᠷᠪᠠᠨ ᠨᠢᠭᠡ"
   "ᠠᠷᠪᠠᠨ ᠬᠣᠶᠠᠷ"])

(def year-suffix " ᠣᠨ")

(def month-suffix " ᠰᠠᠷ᠎ᠠ")

(def day-suffix " ᠡᠳᠥᠷ")