(ns mongol-date-picker.util)

(defn dates [year month]
  (condp = month
    1 31
    ;; (year % 4 == 0 && year % 100 != 0) || year % 400 == 0 ? 29 : 28;
    2 (if (or
           (and (zero? (rem year 4))
                (pos? (rem year 100)))
           (zero? (rem year 400)))
        29
        28)
    3 31
    4 30
    5 31
    6 30
    7 31
    8 31
    9 30
    10 31
    11 30
    12 31
    ;; The function's default value
    30))