(ns mongol-date-picker.util)

(defn format-digit [n digit-type]
  (let [mongol-digits ["᠐" "᠑" "᠒" "᠓" "᠔" "᠕" "᠖" "᠗" "᠘" "᠙"]]
    (if (= digit-type :mongol)
      (->> (str n)
           (map #(let [digit (int (.codeUnitAt % 0))]
                   (nth mongol-digits (- digit 48))))
           (apply str))
      (str n))))

(defn dates [year month]
  (condp = month
    2 (if (or (and (zero? (rem year 4)) (pos? (rem year 100))) (zero? (rem year 400))) 29 28)
    4 30 6 30 9 30 11 30
    31))